name: build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'

    - name: Setup
      run: make setup

    - name: Verify Go Formatting
      run: |
        make fmt
        git diff --exit-code

    - name: Lint
      run: make lint

    - name: Test
      run: make test

    - name: Build
      run: make build

  gui-build-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - uses: ./.github/actions/setup-gui-build

    - name: Build GUI
      run: wails build -tags "gui,webkit2_41"

  goreleaser-check:
    needs: build
    uses: ./.github/workflows/goreleaser.yml
    with:
      goreleaser-args: "build --snapshot --clean"
